name: "Advanced Futuristic Label Automation"

on:
  issues:
    types: [opened, edited, labeled, unlabeled]
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]
  schedule:
    - cron: '0 3 * * *' # Daily sync at 03:00 UTC
  workflow_dispatch:

jobs:
  sync_labels:
    name: "Sync & Protect Labels"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Sync labels from config"
        uses: EndBug/label-sync@v3
        with:
          config-file: .github/labels.json
          delete-other-labels: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Protect critical labels"
        run: |
          gh label edit "critical" --description "Critical issues/blockers" --color "b60205" || true
          gh label edit "security" --description "Security vulnerabilities" --color "d73a4a" || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ai_labeler:
    name: "AI-Powered Label Suggestions"
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: "AI Labeler"
        uses: github/issue-labeler@v4
        with:
          configuration-path: .github/labeler.yml
          enable-versioned-regex: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  multilingual_labeling:
    name: "Multilingual Issue Labeling"
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: "Detect and label language"
        uses: alexeygrigorev/labeler-language@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto_label_pr:
    name: "Autolabel PRs Based on File Paths"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: "Path-based PR Labeler"
        uses: github/auto-label@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/pr-labeler.yml

  # Removed suggest_labels job because the AI-driven label suggestion with OpenAI is hypothetical and not supported in GitHub Actions natively.
  # If you want advanced label suggestions, consider using GitHub's own Copilot-powered features or a third-party integration.

  label_compliance:
    name: "Label Compliance & Analytics"
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: read

    steps:
      - name: "Run label analytics"
        uses: github/label-actions@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/label-actions.yml
